### ISSUE TITLE
Add stream input support

### ISSUE THREAD

**Issue by tsi-trmorris** [RickStrahl/WestWind.WebView.HtmlToPdf#4]
We have a process that we build raw HTML and use this library to generate PDF files. Currently we have to write our generated HTML to a temp file, then use your library to load this. This situation doubles our IO time.

Could you add support to pass in an existing stream of bytes instead of loading a file or remote uri?

**Comment by RickStrahl** [comment]
At first I was going to write this off as not possible because the WebView control itself doesn't support loading content from stream. There's support to load from string, but it's limited to 2mb which can be a problem.

But after giving this some though I did come up with a solution which basically assigns the document content as a string via script command.

```cs
[TestMethod]
public async Task PrintPdfStreamAsyncFromStreamExtendedTest()
{
    // testing with a file based stream but any stream will work
    var sampleFile = Path.GetFullPath("HtmlSampleFileLonger-SelfContained.html");

    PdfPrintResult result;
    using (var stream = new FileStream(sampleFile, FileMode.Open, FileAccess.Read))
    {
        var pdf = new HtmlToPdfHostExtended();
        result = await pdf.PrintToPdfStreamAsync(stream, new WebViewPrintSettings { ScaleFactor = 1F }, Encoding.UTF8);
    }

    Assert.IsTrue(result.IsSuccess, result.Message);

    // display the stream output
    File.Delete(SamplePdf_Outline);
    using (var fstream = new FileStream(SamplePdf_Outline, FileMode.OpenOrCreate, FileAccess.Write))
    {
        result.ResultStream.CopyTo(fstream);
        result.ResultStream.Close(); // Close returned stream!

        ShellUtils.OpenUrl(SamplePdf_Outline);
    }

    Assert.IsNotNull(result, result.Message);
    ShellUtils.OpenUrl(SamplePdf_Outline);
}
```

This has overhead though as the stream has to be converted into a string, and then into a JSON value that then gets embedded into the document. So you're trading the IO overhead with extra memory usage and conversion.
