### ISSUE TITLE
Loading images before generating PDF

### ISSUE THREAD

**Issue by quog** [RickStrahl/WestWind.WebView.HtmlToPdf#6]
Hi Rick,

I have a number of powershell scripts that generate monthly reports for my customers by making a HTML file and then converting it to PDF.  Previously I have done this via calling msedge.exe or chrome.exe with appropriate command line parameters.  However, the latest version of both of those has stopped working for this unless there is no interactive Chrome or Edge running.

Looking for a better solution, I have come across your .net package and have modified your basic consolesample test code to take a file argument.  It works when the images are embedded in the .html (e.g for an .svg style image) but for images such as <img src="x:\dir\dir\file.png"> it seems to be intermittent - sometimes the image is present in the pdf and sometimes note.  When calling msedge or chrome I used "--run-all-compositor-stages-before-draw" which seemed to fix that.

Is there a setting for the webview2 control that will wait for all images to be loaded before generating the pdf similar to that switch?
Or do I need to code the images as data: URLs?

Thanks
Damian

**Comment by RickStrahl** [comment]
Hmmm... The pdf engine renders when the document has completed loading but I'm guessing if you have slow loading images the images may not have loaded by the time the PDF rendering starts.

There's no good way to know when the entire document including its dependencies has loaded beyond the DOMContentLoaded event which in theory should let me know when things like images have loaded.  However, if you dynamically load stuff via script or otherwise inject content, or have very slow loading dependencies DOMContentLoaded won't wait for that.

Personally I've never seen missing image content even on very large documents, because the way the document loads and is rendered it starts at the top and by the time it gets to the end the images likely have loaded. But I can see this failing when images render very slowly.

What I can do is add an optional delay that's fired before the document is 'printed' to PDF that might allow giving a little more time for the document to complete loading. It wouldn't be automatic of course and you'd have to know that content is slow loading.

**Comment by quog** [comment]
In my use case, the .html contains references to images on a network share as (for example) S:\dir\dir\resources\img.png.  They aren't very big but I think it is because of the way they are loaded (there is no webserver, just a generated .html file).  I am going through making all the images inline, either as .svg or as data: urls - these seem to work.

So given there isn't a simple way to  determine if the images are loaded, I wouldn't trouble yourself further.

Thanks anyway.

**Comment by RickStrahl** [comment]
I've added a `DelayPdfGenerationMs` to the `HtmlToPdfHost` class that lets you delay a bit before rendering. 

![image](https://github.com/user-attachments/assets/06f7486f-6dc0-44a6-9491-68700ae83c76)

It might not take a long delay, just long enough for dynamically loaded images to start downloading that might be enough. You can experiment with that. I'd be curious to see if that helps/works.
